<?php
/*
This file is included in functions.php and sets up field groups for the Advanced
Custom Fields Pro plugin.
*/
/*  ==========================================
    SET UP ADVANCED CUSTOM FIELDS FIELD GROUPS
    ========================================== */
function hgnm_custom_field_groups()
{
    acf_add_local_field_group(array(
    'key' => 'group_539c70b07c8ad',
    'title' => 'Colloquia',
    'fields' => array(
        array(
            'key' => 'field_539c7240c1191',
            'label' => 'Use speaker’s full name for title, e.g. “Chaya Czernowin”.',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'If the colloquium is a post-concert discussion, use the performer(s)’s full name, e.g. “ELISION Ensemble” or “Séverine Ballon”.',
            'esc_html' => 0,
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_539c70f2d0e16',
            'label' => 'Colloquium Type',
            'name' => 'colloquium_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'HGNM Member' => 'HGNM Member',
                'Guest Speaker' => 'Guest Speaker',
                'Post-Concert Discussion' => 'Post-Concert Discussion',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'HGNM Member',
            'layout' => 'horizontal',
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_539c713ed0e17',
            'label' => 'HGNM Member',
            'name' => 'fname',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_539c70f2d0e16',
                        'operator' => '==',
                        'value' => 'HGNM Member',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'member',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_539dcc5aba491',
            'label' => 'Which Concert?',
            'name' => 'concert_rel',
            'type' => 'post_object',
            'instructions' => 'Which concert does this colloquium follow and discuss?',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_539c70f2d0e16',
                        'operator' => '==',
                        'value' => 'Post-Concert Discussion',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'concert',
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_539c716dd0e18',
            'label' => 'Guest Speaker’s Personal Website',
            'name' => 'url',
            'type' => 'url',
            'instructions' => 'Website address for the guest speaker, e.g. http://www.fullname.com',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_539c70f2d0e16',
                        'operator' => '==',
                        'value' => 'Guest Speaker',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => 'http://',
            'default_value' => '',
        ),
        array(
            'key' => 'field_539c7213c1190',
            'label' => 'Date',
            'name' => 'dtstart',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_540cc8f474066',
            'label' => 'Colloquium Announcement Flyer',
            'name' => 'photo',
            'type' => 'image',
            'instructions' => 'Upload an image file of the colloquium announcement flyer',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'hgnm-main',
            'library' => 'all',
            'min_width' => 0,
            'min_height' => 0,
            'min_size' => 0,
            'max_width' => 0,
            'max_height' => 0,
            'max_size' => 0,
            'mime_types' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'colloquium',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));

    acf_add_local_field_group(array(
    'key' => 'group_539c5c7f985b6',
    'title' => 'Concerts',
    'fields' => array(
        array(
            'key' => 'field_539c33340295e',
            'label' => 'Use the performer or ensemble name as the title of the concert, e.g. “ELISION Ensemble” or “hand werk”',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'esc_html' => 0,
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_539b14f937947',
            'label' => 'Event Details',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_5397170b0edea',
            'label' => 'Concert Date',
            'name' => 'dtstart',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_53d04a547f12b',
            'label' => 'Concert Time',
            'name' => 'start_time',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'g:i a',
            'return_format' => 'G:i',
        ),
        array(
            'key' => 'field_539b1547a8d9d',
            'label' => 'Venue',
            'name' => 'location',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Paine Hall<br />Harvard University' => 'Paine Hall',
            ),
            'other_choice' => 1,
            'save_other_choice' => 1,
            'default_value' => 'Paine Hall<br />Harvard University',
            'layout' => 'horizontal',
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_54021a0e5e714',
            'label' => 'Is the concert a Goldberg or Fromm residency?',
            'name' => 'support',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Neither' => 'Neither',
                'Fromm' => 'Fromm',
                'Goldberg' => 'Goldberg',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'Neither',
            'layout' => 'horizontal',
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        array(
            'key' => 'field_539b1d6612f14',
            'label' => 'Performer’s personal website',
            'name' => 'performer_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => 'http://',
            'default_value' => '',
        ),
        array(
            'key' => 'field_53bdd228648f6',
            'label' => 'Facebook Event URL',
            'name' => 'facebook_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => 'http://',
            'default_value' => '',
        ),
        array(
            'key' => 'field_539c33ffb6444',
            'label' => 'Summary',
            'name' => 'summary',
            'type' => 'wysiwyg',
            'instructions' => 'Short description of the concert. Composers will be listed elsewhere, so focus on the ensemble, e.g. “HGNM welcome Australia’s leading performers of contemporary music in a programme of new works for wind, brass, guitar and percussion.”',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'tabs' => 'all',
            'delay' => 0,
        ),
        array(
            'key' => 'field_539b14e037946',
            'label' => 'Programme Details',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_539d881cf4335',
            'label' => 'Add audio/video',
            'name' => 'a_v',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Show audio/video embedding options?',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_539c5e6fe8895',
            'label' => 'Programme',
            'name' => 'programme',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add Piece',
            'sub_fields' => array(
                array(
                    'key' => 'field_539c5e9ee8896',
                    'label' => 'Composer',
                    'name' => 'composer',
                    'type' => 'post_object',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'member',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'object',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_539c5ecde8897',
                    'label' => 'Work Title',
                    'name' => 'work_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Work Title',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'formatting' => 'none',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_539c5fecf141d',
                    'label' => 'Embed Link',
                    'name' => 'embed_link',
                    'type' => 'oembed',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_539d881cf4335',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'width' => '',
                    'height' => '',
                ),
                array(
                    'key' => 'field_539d89b16e59c',
                    'label' => 'Audio or Video?',
                    'name' => 'a_or_v',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_539d881cf4335',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'n/a',
                        'Audio' => 'Audio',
                        'Video' => 'Video',
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => 'none',
                    'layout' => 'vertical',
                    'allow_null' => 0,
                    'return_format' => 'value',
                ),
            ),
            'collapsed' => '',
        ),
        array(
            'key' => 'field_539d86606956b',
            'label' => 'Works by non-members',
            'name' => 'programme_plus',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add Piece',
            'sub_fields' => array(
                array(
                    'key' => 'field_55f98c9a8065a',
                    'label' => 'Composer',
                    'name' => 'composer',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Composer’s Full Name',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55f98cbc8065b',
                    'label' => 'Work Title',
                    'name' => 'work_title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'Work Title',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                ),
                array(
                    'key' => 'field_55f98cdf8065c',
                    'label' => 'Embed Link',
                    'name' => 'embed_link',
                    'type' => 'oembed',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_539d881cf4335',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'width' => '',
                    'height' => '',
                ),
                array(
                    'key' => 'field_55f98d128065d',
                    'label' => 'Audio or Video?',
                    'name' => 'a_or_v',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_539d881cf4335',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'n/a',
                        'Audio' => 'Audio',
                        'Video' => 'Video',
                    ),
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'vertical',
                    'allow_null' => 0,
                    'return_format' => 'value',
                ),
            ),
            'collapsed' => '',
        ),
        array(
            'key' => 'field_539c36c46b3ff',
            'label' => 'Archive Material',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_539c36e56b400',
            'label' => 'Programme PDF',
            'name' => 'programme_pdf',
            'type' => 'file',
            'instructions' => 'Upload a PDF of the concert programme once it is available.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'library' => 'all',
            'return_format' => 'array',
            'min_size' => 0,
            'max_size' => 0,
            'mime_types' => '',
        ),
        array(
            'key' => 'field_539c47977df0c',
            'label' => 'Poster PDF',
            'name' => 'poster_pdf',
            'type' => 'file',
            'instructions' => 'Upload a PDF of the concert poster once it is available.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'library' => 'all',
            'return_format' => 'array',
            'min_size' => 0,
            'max_size' => 0,
            'mime_types' => '',
        ),
        array(
            'key' => 'field_53bfaf6f4ba4a',
            'label' => 'Concert Photos',
            'name' => 'gallery',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'min' => '',
            'max' => '',
            'preview_size' => 'thumbnail',
            'library' => 'uploadedTo',
            'min_width' => 0,
            'min_height' => 0,
            'min_size' => 0,
            'max_width' => 0,
            'max_height' => 0,
            'max_size' => 0,
            'mime_types' => '',
            'insert' => 'append',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'concert',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));

    acf_add_local_field_group(array(
    'key' => 'group_539d800c2d788',
    'title' => 'Editorial Guides (Members)',
    'fields' => array(
        array(
            'key' => 'field_539d801827585',
            'label' => 'Editorial Guidelines',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Use the title field (above) for the member’s full name, e.g. “Joanna Smith”, and the field below for the member’s biography.

  Further details should be provided on the right. The featured image field should be used to upload a portrait photograph.',
            'esc_html' => 0,
            'new_lines' => 'wpautop',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'member',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

    acf_add_local_field_group(array(
    'key' => 'group_539c65c537059',
    'title' => 'Member Details',
    'fields' => array(
        array(
            'key' => 'field_539c65df88669',
            'label' => 'Became Member',
            'name' => 'dtstart',
            'type' => 'date_picker',
            'instructions' => 'Year in which this member joined HGNM [Use September 1]',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'Ymd',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_539c66228866a',
            'label' => 'Year Graduated',
            'name' => 'dtend',
            'type' => 'date_picker',
            'instructions' => 'If no longer a current member, year in which this member left HGNM [Use July 1]',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'Ymd',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_539c66498866b',
            'label' => 'Personal Website',
            'name' => 'url',
            'type' => 'url',
            'instructions' => 'Must start with http:// (or https://)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placeholder' => 'http://',
            'default_value' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'member',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'side',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

    acf_add_local_field_group(array(
    'key' => 'group_53ba94605aef9',
    'title' => 'Other Events',
    'fields' => array(
        array(
            'key' => 'field_53ba9460600e2',
            'label' => 'Use the event title, e.g. “HGNM Conference: New Perspectives on New Music” or “HGNM Composers in Lyon”',
            'name' => '',
            'type' => 'message',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => 'Below, add any content that might be relevant to the event.

  N.B. Apart from time and location, you have control over the order of the information on the page. Drag and drop content sections to order information as you’d like it to appear. You can use the ‘Preview Changes’ button to see how things are shaping up.',
            'esc_html' => 0,
            'new_lines' => 'wpautop',
        ),
        array(
            'key' => 'field_53ba9460600fa',
            'label' => 'Event Start Date',
            'name' => 'dtstart',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_53d01b4c3c002',
            'label' => 'Event Start Time',
            'name' => 'start_time',
            'type' => 'time_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'g:i a',
            'return_format' => 'G:i',
        ),
        array(
            'key' => 'field_53ba9c39ef620',
            'label' => 'Event End Date',
            'name' => 'dtend',
            'type' => 'date_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'display_format' => 'm/d/Y',
            'return_format' => 'd/m/Y',
            'first_day' => 1,
        ),
        array(
            'key' => 'field_55fd83ce00f86',
            'label' => 'Event Details',
            'name' => 'details',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'button_label' => 'Add Content',
            'min' => '',
            'max' => '',
            'layouts' => array(
                array(
                    'key' => '55fd83dd43b62',
                    'name' => 'description',
                    'label' => 'Description',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd83ef00f87',
                            'label' => 'Text',
                            'name' => 'summary',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'delay' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => '55fd842d00f88',
                    'name' => 'location',
                    'label' => 'Venue',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd843b00f89',
                            'label' => 'Venue Name',
                            'name' => 'fn',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘Goethe Institut, Boston’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55fd845500f8a',
                            'label' => 'Street',
                            'name' => 'street-address',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘170 Beacon St’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55fd846b00f8b',
                            'label' => 'City',
                            'name' => 'locality',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘Boston’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55fd848100f8c',
                            'label' => 'State/Region',
                            'name' => 'region',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘MA’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55fd849100f8d',
                            'label' => 'ZIP/Post Code',
                            'name' => 'postal-code',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘ 02116’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        array(
                            'key' => 'field_55fd84c000f8e',
                            'label' => 'Country',
                            'name' => 'country-name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'e.g. ‘United States’',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => '55fd84d300f8f',
                    'name' => 'link',
                    'label' => 'External Link',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd84df00f90',
                            'label' => 'URL',
                            'name' => 'url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => 'http://',
                        ),
                        array(
                            'key' => 'field_55fd84fd00f91',
                            'label' => 'Link Text',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 'See event website',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '»',
                            'maxlength' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => '55fd852200f92',
                    'name' => 'photos',
                    'label' => 'Photos',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd852a00f93',
                            'label' => 'Photo Gallery',
                            'name' => 'gallery',
                            'type' => 'gallery',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => '',
                            'max' => '',
                            'preview_size' => 'hgnm-thumb',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'insert' => 'append',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => '55fd859900f94',
                    'name' => 'videos',
                    'label' => 'Videos',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd85a500f95',
                            'label' => 'Videos',
                            'name' => 'videos',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add Video',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_55fd85b500f96',
                                    'label' => 'Embed Link',
                                    'name' => 'embed_link',
                                    'type' => 'oembed',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'width' => '',
                                    'height' => '',
                                ),
                            ),
                            'collapsed' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                array(
                    'key' => '55fd860900f97',
                    'name' => 'documents',
                    'label' => 'Documents',
                    'display' => 'row',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_55fd861800f98',
                            'label' => 'Upload programmes, proceedings, posters etc.',
                            'name' => 'document',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'min' => 0,
                            'max' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add Row',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_55fd862a00f99',
                                    'label' => 'File',
                                    'name' => 'file',
                                    'type' => 'file',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'library' => 'all',
                                    'min_size' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                                array(
                                    'key' => 'field_55fd864c00f9a',
                                    'label' => 'File Name',
                                    'name' => 'file_name',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                    'readonly' => 0,
                                    'disabled' => 0,
                                ),
                            ),
                            'collapsed' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'miscevent',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'seamless',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));
}
add_action('acf/init', 'hgnm_custom_field_groups');
